In [1]:
import numpy as np

In [2]:
# revenue in USD
revenue = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])

In [7]:
# to convert usd to INR where 1USD = 75INR
converted_price = revenue * 75
converted_price

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [8]:
np.array([75])

array([75])

In [9]:
np.multiply(revenue, 75)

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [ ]:
unit_sold = np.array([[50, 60, 25], [10, 13, 5], [42, 140, 180], [80, 85, 90]])